### ISSUE TITLE
Bug on startup

### ISSUE THREAD

**Issue by GamingWithRaf** [Gaming32/ArrayV#99]
So I opened the .jar file and started using ArrayV. However I got this error:

**java.io.IOException: mark/reset not supported
	at java.util.zip.InflaterInputStream.reset(Unknown Source)
	at java.io.FilterInputStream.reset(Unknown Source)
	at com.sun.media.sound.AudioFileSoundbankReader.getSoundbank(Unknown Source)
	at javax.sound.midi.MidiSystem.getSoundbank(Unknown Source)
	at io.github.arrayv.utils.Sounds.loadInstruments(Sounds.java:346)
	at io.github.arrayv.utils.Sounds.prepareDefaultSoundbank(Sounds.java:276)
	at io.github.arrayv.utils.Sounds.<init>(Sounds.java:156)
	at io.github.arrayv.main.ArrayVisualizer.<init>(ArrayVisualizer.java:475)
	at io.github.arrayv.main.ArrayVisualizer.main(ArrayVisualizer.java:1526)**

**Comment by GamingWithRaf** [comment]
> What version of ArrayV do you have?

5.1
